/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "contact-us": {
        "export": {
            "type": string;
            "name": string;
            "phone": string;
            "email": string;
            "dealer": string;
            "region": string;
            "annualSalesVolume": string;
            "expectedPurchaseDate": string;
            "postalCode": string;
            "city": string;
            "crmCityCode": string;
            "country": string;
            "vehicleType": string;
            "vehicleVin": string;
            "carColor": string;
            "message": string;
            "createTime": string;
        };
        "type": {
            "BUSINESS": string;
            "BUSINESS_DEALER": string;
            "BUSINESS_CORPORATE_FLEET": string;
            "BUSINESS_SUPPLY_TECH": string;
            "BUSINESS_BRAND": string;
            "PURCHASE_INTENTION": string;
            "SERVICE_SUPPORT": string;
            "WEBSITE_BUILDING": string;
            "TEST_DRIVE": string;
        };
        "validation": {
            "duplicate_submission": string;
        };
    };
    "user": {
        "not.exists": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
